<a href="https://colab.research.google.com/github/limhasic/TimeSeries_Anomaly_Detection/blob/main/%EB%94%B0%EB%9D%BC%ED%81%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kaggle # kaggle 라이브러리 설치
from google.colab import files # colab 라이브러리 가져오기 
files.upload()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2022.6.15)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.2)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"hasiclim","key":"9f64a79ffe5ffd4a8c6e5624af84e49f"}'}

In [2]:
# Kaggle 폴더 생성
# kaggle.json 파일 이동

!mkdir -p ~/.kaggle 
!cp kaggle.json ~/.kaggle/
# 나에 대한 읽기(4) 쓰기(1) 권한부여 설정
!chmod 600 ~/.kaggle/kaggle.json

In [3]:
!kaggle datasets download -d sudalairajkumar/novel-corona-virus-2019-dataset
!unzip -q /content/novel-corona-virus-2019-dataset.zip

Downloading novel-corona-virus-2019-dataset.zip to /content
 59% 5.00M/8.52M [00:01<00:00, 4.40MB/s]
100% 8.52M/8.52M [00:01<00:00, 7.39MB/s]

In [4]:
# 먼저, 데이터에 대해 살펴 본다면, 

import pandas as pd 
confirmed  = pd.read_csv("/content/time_series_covid_19_confirmed.csv")

            160
1/22/20       1
1/23/20       1
1/24/20       2
1/25/20       2
1/26/20       3
...         ...
5/25/21  137682
5/26/21  138311
5/27/21  138898
5/28/21  139431
5/29/21  139910

[494 rows x 1 columns]

In [16]:
confirmed

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21,5/28/21,5/29/21
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,64575,65080,65486,65728,66275,66903,67743,68366,69130,70111
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,132118,132153,132176,132209,132215,132229,132244,132264,132285,132297
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,126156,126434,126651,126860,127107,127361,127646,127926,128198,128456
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,13569,13569,13569,13569,13569,13664,13671,13682,13693,13693
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,31661,31909,32149,32441,32623,32933,33338,33607,33944,34180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,NaN,Vietnam,14.058324,108.277199,0,2,2,2,2,2,...,4809,4941,5119,5275,5404,5931,6086,6356,6396,6908
272,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,304532,304968,305201,305201,305777,306334,306795,306795,307569,307838
273,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,6613,6632,6649,6658,6662,6670,6688,6696,6723,6731
274,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,92754,92920,93106,93201,93279,93428,93627,93947,94430,94751
275,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,38635,38664,38679,38682,38696,38706,38819,38854,38918,38933

In [ ]:
# 494 ( 2020년 1월 22일 부터, 2021년 5월 29일 까지 )

confirmed[confirmed['Country/Region'] == "Korea, South"].T[4:]